# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_get_range_by_bound <- function(R_sx, R_l, R_h) {
    .Call(`_exceedance_C_get_range_by_bound`, R_sx, R_l, R_h)
}

C_GW_compute_FDR <- function(sorted_i, R_P, R_Q, rj_num, n) {
    .Call(`_exceedance_C_GW_compute_FDR`, sorted_i, R_P, R_Q, rj_num, n)
}

C_get_range_by_bound2 <- function(R_sx, R_l, R_h) {
    .Call(`_exceedance_C_get_range_by_bound2`, R_sx, R_l, R_h)
}

general_GW_construct_subset <- function(pvalue_func, rho, x) {
    .Call(`_exceedance_general_GW_construct_subset`, pvalue_func, rho, x)
}

general_GW_compute_FP <- function(ptr, m, sorted_i, alpha) {
    .Call(`_exceedance_general_GW_compute_FP`, ptr, m, sorted_i, alpha)
}

print_subset_list <- function(x) {
    invisible(.Call(`_exceedance_print_subset_list`, x))
}

compute_prob <- function(m, R_g_value, R_h_value, n_t, R_diff_t) {
    .Call(`_exceedance_compute_prob`, m, R_g_value, R_h_value, n_t, R_diff_t)
}

compute_prob_fft <- function(m, R_g_value, R_h_value, n_t, R_diff_t) {
    .Call(`_exceedance_compute_prob_fft`, m, R_g_value, R_h_value, n_t, R_diff_t)
}

